#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/kptdobe/helix-templates.git#master

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/kptdobe/helix-templates-content.git#master
    static: https://github.com/kptdobe/helix-templates.git/htdocs#master
